name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: roxsross12
  IMAGE_NAME: demo-app

jobs:

  build_test:
    runs-on: ubuntu-latest
    
    strategy: 
     matrix:
       node-version: [12.x]    
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
      
      # test the apps     
      - name: test
        run: |
          npm run test   
          
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build_test]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
